
services:
  # TradeMachineEx Application (Production)
  app:
    image: ${IMAGE_TAG:-ghcr.io/akosasante/trade-machine-ex:latest}
    container_name: trade_machine_ex_app
    network_mode: "host" # Needed to connect to host's PostgreSQL
    environment:
      - MIX_ENV=prod
      - PORT=4001

      # Database configuration (external PostgreSQL)
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME:-trade_machine}
      - DATABASE_PORT=${DATABASE_PORT:-5432}
      - DATABASE_POOL_SIZE=${DATABASE_POOL_SIZE:-10}
      - DATABASE_SCHEMA=${DATABASE_SCHEMA:-staging}

      # Phoenix configuration
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PHX_HOST=${PHX_HOST}

      # Release configuration
      - RELEASE_COOKIE=${RELEASE_COOKIE}

      # Logging configuration
      - LOG_LEVEL=${LOG_LEVEL:-info}

      # Google Sheets integration (optional)
      - GOOGLE_SHEETS_CREDS_PATH=${GOOGLE_SHEETS_CREDS_PATH:-}
      - GOOGLE_SPREADSHEET_ID=${GOOGLE_SPREADSHEET_ID:-}

      # Job processing configuration
      - ENABLE_CRON=${ENABLE_CRON:-false}
      - OBAN_MINORS_SYNC_CONCURRENCY=${OBAN_MINORS_SYNC_CONCURRENCY:-1}
      - OBAN_DRAFT_SYNC_CONCURRENCY=${OBAN_DRAFT_SYNC_CONCURRENCY:-1}

      # Monitoring configuration
      - GRAFANA_HOST=${GRAFANA_HOST:-}
      - GRAFANA_TOKEN=${GRAFANA_TOKEN:-}

      # Email configuration (Brevo/SendInBlue) and data needed to populate emails
      - BREVO_API_KEY=${BREVO_API_KEY}
      - FRONTEND_URL=${FRONTEND_URL:-trades.flexfoxfantasy.com}

    # Resource limits for production
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    labels:
      - "service=trade_machine_ex"
      - "environment=production"
      - "com.centurylinklabs.watchtower.enable=true"