
services:
  # TradeMachineEx Application
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"  # Phoenix application (includes /metrics endpoint via PromEx plug)
    environment:
      - MIX_ENV=dev
      - PORT=${PORT}
      - METRICS_PORT=${METRICS_PORT}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_PORT=${DATABASE_PORT}
      - DATABASE_POOL_SIZE=${DATABASE_POOL_SIZE}
      - DATABASE_SCHEMA=${DATABASE_SCHEMA}
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PHX_HOST=${PHX_HOST}
      - LOG_LEVEL=${LOG_LEVEL}
      - GOOGLE_SHEETS_CREDS_PATH=${GOOGLE_SHEETS_CREDS_PATH}
      - GOOGLE_SPREADSHEET_ID=${GOOGLE_SPREADSHEET_ID}
      - ENABLE_CRON=${ENABLE_CRON}
      - OBAN_MINORS_SYNC_CONCURRENCY=${OBAN_MINORS_SYNC_CONCURRENCY}
      - OBAN_DRAFT_SYNC_CONCURRENCY=${OBAN_DRAFT_SYNC_CONCURRENCY}
      - GRAFANA_HOST=${GRAFANA_HOST}
      - GRAFANA_TOKEN=${GRAFANA_TOKEN}
      - GRAFANA_UPLOAD_DASHBOARDS=${GRAFANA_UPLOAD_DASHBOARDS}
      - GIT_SHA=${GIT_SHA}
    volumes:
      # Mount source code for development
      - .:/app
      - /app/_build
      - /app/deps
      - /app/assets/node_modules
      # Mount Google Sheets credentials if available locally
      - ${GOOGLE_SHEETS_CREDS_FILE:-./sheet_creds.json}:/app/sheet_creds.json:ro
    networks:
      # Connect to shared infrastructure network
      - trade_machine_shared
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    # Note: No depends_on since external services might not be defined in this compose file

# Use the shared infrastructure network
networks:
  trade_machine_shared:
    external: true
    name: trade_machine_shared