
services:
  # TradeMachineEx Application (Production)
  app:
    image: ${IMAGE_TAG:-ghcr.io/akosasante/trade-machine-ex:latest}
    ports:
      - "4001:4000"  # Phoenix application
      - "9090:9090"  # Prometheus metrics
    environment:
      - MIX_ENV=prod
      - PORT=4000

      # Database configuration (external PostgreSQL)
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME:-trade_machine}
      - DATABASE_PORT=${DATABASE_PORT:-5432}
      - DATABASE_POOL_SIZE=${DATABASE_POOL_SIZE:-10}
      - DATABASE_SCHEMA=${DATABASE_SCHEMA:-staging}

      # Phoenix configuration
      - SECRET_KEY_BASE=${SECRET_KEY_BASE}
      - PHX_HOST=${PHX_HOST}

      # Logging configuration
      - LOG_LEVEL=${LOG_LEVEL:-info}

      # Google Sheets integration (optional)
      - GOOGLE_SHEETS_CREDS_PATH=${GOOGLE_SHEETS_CREDS_PATH:-}
      - GOOGLE_SPREADSHEET_ID=${GOOGLE_SPREADSHEET_ID:-}

      # Job processing configuration
      - ENABLE_CRON=${ENABLE_CRON:-false}
      - OBAN_MINORS_SYNC_CONCURRENCY=${OBAN_MINORS_SYNC_CONCURRENCY:-1}
      - OBAN_DRAFT_SYNC_CONCURRENCY=${OBAN_DRAFT_SYNC_CONCURRENCY:-1}

      # Monitoring configuration
      - GRAFANA_HOST=${GRAFANA_HOST:-}
      - GRAFANA_TOKEN=${GRAFANA_TOKEN:-}

    volumes:
      # Mount log directory for external log collection
      - app_logs:/var/log/trade_machine_ex

    networks:
      - trade_machine_network

    # Resource limits for production
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1.0'
        reservations:
          memory: 256M
          cpus: '0.5'
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
        labels: "service,environment"

    labels:
      - "service=trade_machine_ex"
      - "environment=production"
      - "com.centurylinklabs.watchtower.enable=true"

  # Optional: Grafana Alloy for metrics and log collection
  alloy:
    image: grafana/alloy:latest
    ports:
      - "12345:12345"  # Alloy UI
    command:
      - run
      - /etc/alloy/config.alloy
      - --server.http.listen-addr=0.0.0.0:12345
      - --storage.path=/var/lib/alloy/data
    environment:
      - HOSTNAME=${HOSTNAME:-trade-machine-ex}
    volumes:
      - ./docker/alloy/config.alloy:/etc/alloy/config.alloy:ro
      - app_logs:/var/log/trade_machine_ex:ro
      - alloy_data:/var/lib/alloy/data
    networks:
      - trade_machine_network
    profiles:
      - observability
    depends_on:
      - app

volumes:
  app_logs:
    driver: local
  alloy_data:
    driver: local

networks:
  trade_machine_network:
    driver: bridge
    labels:
      - "service=trade_machine_ex"