global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # TradeMachineEx application metrics
  - job_name: 'trade_machine_ex'
    static_configs:
      - targets: ['app:9090']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s
    scheme: http
    static_configs:
      - targets: ['app:9090']
        labels:
          service: 'trade_machine_ex'
          environment: 'development'
          instance: 'app:9090'

  # PostgreSQL exporter (if added later)
  # - job_name: 'postgres'
  #   static_configs:
  #     - targets: ['postgres_exporter:9187']

  # Redis exporter (if added later)
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis_exporter:9121']