name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  MIX_ENV: test

jobs:
  test:
    name: Test & Code Quality
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: trader_test
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: trade_machine_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432


    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18.0'
          otp-version: '27.1'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Set up Node.js (for Prisma)
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Prisma CLI
        run: npm install -g prisma

      - name: Download Prisma schema from TypeScript server
        run: |
          mkdir -p prisma
          curl -o prisma/schema.prisma https://raw.githubusercontent.com/${{ github.repository_owner }}/TradeMachineServer/main/prisma/schema.prisma

      - name: Run Prisma migrations
        run: |
          export DATABASE_URL="postgresql://trader_test:test_password@localhost:5432/trade_machine_test?schema=test"
          prisma db push --force-reset

      - name: Install dependencies
        run: mix deps.get

      - name: Check code formatting
        run: mix format --check-formatted

      - name: Run Credo linter
        run: mix credo

      - name: Compile
        run: mix compile

      - name: Run tests
        run: mix test
        env:
          DATABASE_HOST: localhost
          DATABASE_USER: trader_test
          DATABASE_PASSWORD: test_password
          DATABASE_NAME: trade_machine_test
          DATABASE_PORT: 5432
          DATABASE_SCHEMA: test
          SCHEMA: test